- name: Stop Valheim service
  become: yes
  ansible.builtin.systemd:
    name: valheim
    state: stopped

- name: Update valheim server
  command:
    cmd: >
      ./steamcmd/steamcmd.sh 
        +@sSteamCmdForcePlatformType linux 
        +force_install_dir valheim_server 
        +login anonymous 
        +app_update 896660 validate 
        +quit

- name: Start Valheim service
  become: yes
  ansible.builtin.systemd:
    name: valheim
    state: started
