- name: Create systemd unit file
  become: yes
  ansible.builtin.template:
    src: valheim.service
    dest: /etc/systemd/system/valheim.service

- name: Create update script
  ansible.builtin.copy:
    src: do-update.sh
    dest: do-update.sh
    mode: "0755"

- name: Create systemd unit file
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  loop:
    - valheim-update.service
    - valheim-update.timer

- name: Ensure valheim update timer is enabled
  become: yes
  ansible.builtin.systemd:
    name: valheim-update.timer
    enabled: yes
    state: started

- name: Ensure valheim service is enabled
  become: yes
  ansible.builtin.systemd:
    name: valheim
    enabled: yes
